<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product view template
 *
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_product = $block->getProduct();

$_attributeLabel = $_product->getResource()->getAttribute('raww_new');

$_attributeLabel = $_attributeLabel->getFrontend()->getValue($_product);
if ($_attributeLabel) {
    if (strtolower($_attributeLabel) == 'new') { ?>
        <div class="raww-new">
            <span>
               <?= $_attributeLabel ?>
            </span>
        </div>
    <?php } elseif (strtolower($_attributeLabel) == 'new shade') { ?>
        <div class="raww-newshade">
            <span>
                <? $_attributeLabel ?>
            </span>
        </div>
    <?php }
} else { ?>
    <div class="not-rawnew">
        <span>
           <?= '' ?>
        </span>
    </div>
<?php }
?>